### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by HeadClot** [jaybennett89/thorium-go#5]
Hey @jaybennett89 
Would it be possible to get a License file for Thorium-Go?

I am looking at using this for my own personal projects with both Unreal 4 and the EnGO game engines.

Thank you for your time,
HeadClot

**Comment by jaybennett89** [comment]
Hi @HeadClot,

I am happy to add a license file for you. This project is now released under the MIT license.

The project is built to be game engine agnostic. The only requirements to work with this project are:

1) Your game server application can be launched from the command line and read the input arguments
2) Your game client and server can make HTTP requests 
3) Your game client and server can read and write JSON

I think Unreal 4 will work for sure, but I'm not familiar with the EnGO engine. 

The next thing I'm working on is a new startup guide. I introduced Docker Compose recently which makes things a little more complicated to install and configure. I'm hoping to clarify the "getting started" process and update the documentation.

You can run the tests by running "go test" in the /client directory. It's an integration test which requires the service to be correctly running to pass. So that will help you make sure that you got everything started correctly!

**Comment by HeadClot** [comment]
Hey @jaybennett89 - Thank you for the license file. It really means allot.

Cannot wait for that startup guide. I will be watching closely.

Thank you again,
HeadClot
